const Application = require('../models/Application');

// SUBMIT AN APPLICATION (Candidate Only)
exports.applyForJob = async (req, res) => {
  try {
    const { jobId } = req.body;
    
    // Check if the file was successfully uploaded to Cloudinary
    if (!req.file) {
      return res.status(400).json({ message: 'Please upload a resume' });
    }

    // req.file.path contains the secure Cloudinary URL generated by our storage engine
    const resumeUrl = req.file.path; 

    // Check if user already applied
    const existingApplication = await Application.findOne({ job: jobId, candidate: req.user.id });
    if (existingApplication) {
      return res.status(400).json({ message: 'You have already applied for this position.' });
    }

    const newApplication = new Application({
      job: jobId,
      candidate: req.user.id,
      resumeUrl: resumeUrl, // Storing ONLY the URL as per instructions [cite: 192]
      status: 'Submitted'
    });

    await newApplication.save();
    res.status(201).json({ message: 'Application submitted successfully!', application: newApplication });

  } catch (error) {
    res.status(500).json({ message: 'Error submitting application', error: error.message });
  }
};
